package world.bentobox.acidisland.listeners;

import java.util.Objects;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.World;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockFormEvent;

import world.bentobox.acidisland.AcidIsland;
import world.bentobox.bentobox.util.Util;


public class LavaCheck implements Listener {

    private final AcidIsland addon;


    public LavaCheck(AcidIsland addon) {
        this.addon = addon;
    }

    /**
     * Removes stone generated by lava pouring on water
     *
     * @param e - event
     */
    @EventHandler(priority = EventPriority.LOWEST)
    public void onCleanStoneGen(BlockFormEvent e) {
        World world = Util.getWorld(e.getBlock().getWorld());
        int seaHeight;
        if (addon.getOverWorld().equals(world)) {
            seaHeight = addon.getSettings().getSeaHeight();
        } else if (Objects.equals(addon.getNetherWorld(), world)) {
            seaHeight = addon.getSettings().getNetherSeaHeight();
        } else if (Objects.equals(addon.getEndWorld(), world)) {
            seaHeight = addon.getSettings().getEndSeaHeight();
        } else {
            return;
        }
        if (!e.getBlock().getType().equals(Material.WATER)
            || !addon.getOverWorld().equals(world)
            || addon.getSettings().getAcidDamage() <= 0
            || e.getBlock().getLocation().getY() > seaHeight) {
            return;
        }
        if (e.getNewState().getType().equals(Material.STONE)) {
            e.setCancelled(true);
            e.getBlock().getWorld().playSound(e.getBlock().getLocation(), Sound.ENTITY_CREEPER_PRIMED, 1F, 2F);
        }
    }


}
